# Generated by Django 4.2 on 2026-01-23 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoPrueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_prueba', models.CharField(choices=[('lectura', 'Prueba de Lectura'), ('velocidad', 'Prueba de Velocidad'), ('comprension', 'Prueba de Comprensión'), ('ortografia', 'Prueba de Ortografía')], max_length=20)),
                ('puntaje', models.IntegerField(help_text='Puntaje obtenido en la prueba (0-100)')),
                ('fecha_prueba', models.DateTimeField(auto_now_add=True)),
                ('duracion_segundos', models.IntegerField(default=0, help_text='Duración de la prueba en segundos')),
                ('detalles', models.JSONField(blank=True, default=dict, help_text='Detalles adicionales de la prueba')),
                ('estado', models.CharField(choices=[('completada', 'Completada'), ('incompleta', 'Incompleta'), ('cancelada', 'Cancelada')], default='completada', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_pruebas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resultado de Prueba',
                'verbose_name_plural': 'Resultados de Pruebas',
                'ordering': ['-fecha_prueba'],
            },
        ),
    ]
