# Generated by Django 4.2 on 2026-08-22 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='institution',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Institución'),
        ),
        migrations.AddField(
            model_name='profile',
            name='license_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Matrícula profesional'),
        ),
        migrations.AddField(
            model_name='profile',
            name='specialty',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Especialidad'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='resultadoprueba',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
