# Generated by Django 4.2 on 2026-08-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_profile_institution_profile_license_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_office_patient',
            field=models.BooleanField(default=False, verbose_name='Paciente en consultorio'),
        ),
    ]
