# Generated by Django 4.2 on 2026-09-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_resultadoprueba_alfabeto_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadoprueba',
            name='tipo_prueba',
            field=models.CharField(choices=[('lectura', 'Prueba de Lectura'), ('velocidad', 'Prueba de Velocidad'), ('comprension', 'Prueba de Comprensión'), ('ortografia', 'Prueba de Ortografía'), ('alfabeto', 'Filtro de Conocimiento: Alfabeto'), ('parejas', 'Juego: Parejas escondidas'), ('silabas', 'Juego: El tren de sílabas'), ('letras', 'Juego: Lluvia de letras')], max_length=20),
        ),
    ]
