# Generated by Django 4.2 on 2026-09-29 15:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


PRUEBAS = {
    'lectura': ('Prueba de Lectura', 'evaluacion'),
    'velocidad': ('Prueba de Velocidad', 'evaluacion'),
    'comprension': ('Prueba de Comprensión', 'evaluacion'),
    'ortografia': ('Prueba de Ortografía', 'evaluacion'),
    'alfabeto': ('Filtro de Conocimiento: Alfabeto', 'filtro'),
    'parejas': ('Juego: Parejas escondidas', 'juego'),
    'silabas': ('Juego: El tren de sílabas', 'juego'),
    'letras': ('Juego: Lluvia de letras', 'juego'),
}


def migrar_datos_normalizados(apps, schema_editor):
    Profile = apps.get_model('usuarios', 'Profile')
    Paciente = apps.get_model('usuarios', 'Paciente')
    Profesional = apps.get_model('usuarios', 'Profesional')
    TipoPrueba = apps.get_model('usuarios', 'TipoPrueba')
    ResultadoPrueba = apps.get_model('usuarios', 'ResultadoPrueba')

    catalogo = {
        codigo: TipoPrueba.objects.create(codigo=codigo, nombre=nombre, categoria=categoria)
        for codigo, (nombre, categoria) in PRUEBAS.items()
    }
    for perfil in Profile.objects.all():
        if perfil.role == 'paciente':
            Paciente.objects.create(
                profile=perfil,
                ci=perfil.ci,
                age=perfil.age,
                is_office_patient=perfil.is_office_patient,
            )
        elif perfil.role == 'doctor':
            Profesional.objects.create(
                profile=perfil,
                license_number=perfil.license_number,
                specialty=perfil.specialty,
                institution=perfil.institution,
            )
    for resultado in ResultadoPrueba.objects.all():
        resultado.prueba = catalogo[resultado.tipo_prueba]
        resultado.save(update_fields=['prueba'])


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_resultadoprueba_tipo_prueba'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('categoria', models.CharField(default='evaluacion', max_length=30)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de prueba',
                'verbose_name_plural': 'Tipos de prueba',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(blank=True, default='', max_length=100, verbose_name='Matrícula profesional')),
                ('specialty', models.CharField(blank=True, default='', max_length=150, verbose_name='Especialidad')),
                ('institution', models.CharField(blank=True, default='', max_length=200, verbose_name='Institución')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profesional', to='usuarios.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(blank=True, help_text='Identificador único del paciente', max_length=64, null=True, unique=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Edad')),
                ('is_office_patient', models.BooleanField(default=False, verbose_name='Paciente en consultorio')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='usuarios.profile')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100)),
                ('respuesta', models.JSONField(blank=True, default=dict)),
                ('puntaje', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='usuarios.resultadoprueba')),
            ],
        ),
        migrations.AddField(
            model_name='resultadoprueba',
            name='prueba',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='usuarios.tipoprueba'),
        ),
        migrations.RunPython(migrar_datos_normalizados, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ci',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_office_patient',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='resultadoprueba',
            name='tipo_prueba',
        ),
        migrations.AlterField(
            model_name='resultadoprueba',
            name='prueba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='usuarios.tipoprueba'),
        ),
        migrations.AddConstraint(
            model_name='respuestaresultado',
            constraint=models.UniqueConstraint(fields=('resultado', 'clave'), name='respuesta_por_clave_unica'),
        ),
    ]
