# Generated by Django 4.2 on 2026-09-29 15:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def migrar_resultados_a_pacientes(apps, schema_editor):
    ResultadoPrueba = apps.get_model('usuarios', 'ResultadoPrueba')
    Paciente = apps.get_model('usuarios', 'Paciente')

    for resultado in ResultadoPrueba.objects.all():
        paciente = Paciente.objects.filter(profile__user_id=resultado.usuario_id).first()
        if paciente is None:
            raise RuntimeError(
                f'No se puede migrar el resultado {resultado.pk}: '
                'su usuario no tiene un registro de Paciente.'
            )
        resultado.paciente_id = paciente.pk
        resultado.save(update_fields=['paciente'])


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_tipoprueba_remove_profile_age_remove_profile_ci_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoprueba',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultados_pruebas', to='usuarios.paciente'),
        ),
        migrations.RunPython(migrar_resultados_a_pacientes, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='resultadoprueba',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='resultadoprueba',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_pruebas', to='usuarios.paciente'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Matrícula profesional'),
        ),
        migrations.AlterField(
            model_name='resultadoprueba',
            name='puntaje',
            field=models.IntegerField(help_text='Puntaje obtenido en la prueba (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(check=models.Q(('role__in', ['admin', 'doctor', 'paciente'])), name='profile_role_valido'),
        ),
    ]
